### ISSUE TITLE
Add support for forecast.io and openweathermap

### ISSUE THREAD

**Issue by marksev1** [caternuson/rpi-weather#3]
If possible could you please add the above free weather api providers since those are more useful for us guys that don't live in the USA.

**Comment by caternuson** [comment]
Done. Give it a try. There are separate programs for each service. The readme has been updated with instructions.

**Comment by marksev1** [comment]
Wow that was fast I don't even have the hardware yet :). Thanks for doing
it! When I get the hardware I'll test it out and let you know.

Btw any way in the code to specify less than 4 LED matrixes?

2016-07-28 5:29 GMT+02:00 Carter Nelson notifications@github.com:

**Comment by caternuson** [comment]
Closing for now.

Sorry. Code is hardwired for 4 LED matrices.

**Comment by dwburke** [comment]
When I was tinkering a couple weeks ago, I was able to support less by changing the hard-coded 4's to NUM_DAYS
