### ISSUE TITLE
Added support for metoffice.gov.uk

### ISSUE THREAD

**Issue by will675** [caternuson/rpi-weather#4]
Fantastic project, looks very cool!

I have created a new integration with the `metoffice.gov.uk` site but github isn't letting me create a branch or a pull-request, so have attached it here.
[weather_metoffice.zip](https://github.com/caternuson/rpi-weather/files/410410/weather_metoffice.zip)

Think I'm also going to have to try and come up with some more icons, turns out we have a lot of different words for rain over here... :-)

In the weather.cfg file you need an API_KEY (free to sign up and get) and a LOCATION_ID.  To get that you need to hit this url:
http://datapoint.metoffice.gov.uk/public/data/val/wxfcs/all/json/sitelist?key=[YOUR_API_KEY_HERE]

and search for your nearest location.  If you can't find the location you are after you can hit the main site (http://www.metoffice.gov.uk) and use their front-end search to find the closest location they have, then get the code for that from the api response above.

Hope this is useful.  I'd like to put together a step-by-step guide on the wiki when I get a chance, if you don't mind, this project deserves one!

**Comment by will675** [comment]
Ah, looks like i fork this project, make my changes and then create the pull-request from there.  Will try that when I get a chance.

Also noticed you have updated the github.io site to include a fritzing file so probably as clear a guide as needed on that hardware side.  If you want I could add some detail on the software side; how to go from a complete start on the RPi, from installing Raspbian-Lite to getting i2c working etc (having just been through it myself the last couple of nights...)

**Comment by caternuson** [comment]
Merged. Thanks.

I did not get an API key to test it, but it looks OK. Assuming @will675 has proven it works.

Basic RPi config should be covered elsewhere (raspbian install, i2c, etc.), and I'd hope already is. Also, I'm currently using the gh-pages feature of github over the wiki for how-to info:
http://caternuson.github.io/rpi-weather/
