### ISSUE TITLE
Details on the glass

### ISSUE THREAD

**Issue by otherguy** [caternuson/rpi-weather#8]
Hi! Could you tell me what kind of glass you used? Is it black painted real glass or black plexiglass? How thick is it and what is the transmissibility of the glass?

**Comment by caternuson** [comment]
It was a scrap piece of dark green glass from a local building supply scrap recycle store. You can see it here:
http://caternuson.github.io/rpi-weather/
Click the gear icon to go to the build photos. It's the item labeled 5. It may look like an opaque piece of black plastic, but it is actually glass and transmits the LEDs OK. It's just a very dark piece of glass, so normal light levels don't go through and you can't see the matrices behind the glass. Anything similar should work.

Hope that helps.

**Comment by otherguy** [comment]
Very cool, thanks!

I’ve see the photo before posting here but it looks completely black. 

I’ll check the scrap pile in my home supply store!

**Comment by caternuson** [comment]
Checkout this as another option:
https://www.tapplastics.com/product/plastics/cut_to_size_plastic/black_led_sheet/668
Although that will diffuse the LEDs as well, so will look "fuzzy".

**Comment by otherguy** [comment]
Oh that could be cool too! 

Since you said your glass is green(ish), I assume your LED matrices are white and just look yellow in the photos?

**Comment by caternuson** [comment]
I think the LEDs were maybe yellow? Can't recall. They come in different colors. So it's just an aesthetic choice. But you will want to consider LED color + glass color to a certain extent. The actual end results can be tricky to predict though. I think I started with the LEDs and then just tried different glass scraps until I got a result I liked.
